### ISSUE TITLE
Wireframe and content in resources.md do not match

### ISSUE THREAD

**Issue by monasobh** [fontvu/BTU-WebDocs-WS22#24]
Hi, 

we have a few questions while developing your website.

1. in your recources.md file you have an image for the "Home" site. Although on your wireframe you only want text (some intro words). Please let us know ASAP what you prefer. 
2. in your resource.md file you have content (text and image) for 3 services although in your wireframe you have 4 services. Do you have three or four services i.e. are we missing text & image for service 4?
3. For each service site the content is missing. Please provide us witht the content of the products on each site.
4. the images for the blog are not in the recouces.md file. Please provide us with those images.
5. For the "about us" page you only have two members on your wireframe. We assume that you meant three placeholders for each member and we will implement this accordingly. 

Everywhere where your text is missing, we will put Lorem Ipsum (just some random text-placeholder) and wait for you to provide us with the content.

Thanks!

**Comment by venttis-1** [comment]
for 2. you can find the text under https://github.com/fontvu/BTU-WebDocs-WS22/issues/14

**Comment by jaylin0114** [comment]
Hi @monasobh, thanks for your feedback.

For 1, we prefer using the home image as the background for the whole website.

**Comment by monasobh** [comment]
> for 2. you can find the text under #14

so #14 is your fourth service? And what image should we use?

**Comment by monasobh** [comment]
> Hi @monasobh, thanks for your feedback.
> 
> For 1, we prefer using the home image as the background for the whole website.

This image is really dark. How do you want to have the "some intro words" on this picture?? I have a suggestion to include this image, please let me know if you agree.

<img width="1440" alt="Screenshot 2023-01-08 at 20 57 22" src="https://user-images.githubusercontent.com/49497676/211216190-6e8e7ac3-c3a4-4d50-9b41-00ab612d00b2.png">

**Comment by jaylin0114** [comment]
@monasobh I think you are right. We welcome any ideas and suggestions. Please share them with us, thank you.
