### ISSUE TITLE
Request for making small changes for your logo

### ISSUE THREAD

**Issue by monasobh** [fontvu/BTU-WebDocs-WS22#26]
Dear client,

as we are working on your User Interface for your website we have a suggestion regarding your logo. 

Your provided logo:
<img width="251" alt="Screenshot 2023-01-08 at 21 13 49" src="https://user-images.githubusercontent.com/49497676/211216965-b78f23cd-a445-40d0-8e8b-1cec27a99ce3.png">

Small changes made regarding the distance of the signs within the screen and centering it:
<img width="256" alt="Screenshot 2023-01-08 at 21 13 36" src="https://user-images.githubusercontent.com/49497676/211216949-c270e987-e8db-4a2f-8db7-b7d1e2e42684.png">

Please let us know if you are okay with those small changes. Thanks!

**Comment by fontvu** [comment]
Yes please make that change, much appreciated.
