### ISSUE TITLE
Please review first prototype

### ISSUE THREAD

**Issue by monasobh** [fontvu/BTU-WebDocs-WS22#28]
Dear clients,

you can now review the first prototype here: https://fontvu.github.io/BTU-WebDocs-WS22/index.html 

Please give us some feedback, in case you have additional wishes or would like some changes. 

Some information for you regarding our implementation:
- We adapted a few pages according to the content we got from you. (E.g. manufactoring and all other publications each have only one report not 4 as on your wireframe). Therefore we only provide one download option for one report.

- You didn't provdie us with a category of your Blog posts thats why we used the date as a headline.

- As you only have three small sentences for your "About us" page we would suggest here to not implement a navigation as it may be overhead for the page. 

- We renamed "left, middle and right guy" and put Lorem Ipsum as name. 

Regards,
your developers

**Comment by monasobh** [comment]
@jaylin0114 @fontvu @venttis-1 Hi, please remember to give us some feedback before the submission tonight. Thanks!

**Comment by jaylin0114** [comment]
Hi,

Sorry that I left my comments in Issue#32. Other than that, I am fine with
the prototype. Thanks for your effort.

**Comment by monasobh** [comment]
Thank you for your feedback!
