### ISSUE TITLE
Suggestion to remove breadcrumbs

### ISSUE THREAD

**Issue by monasobh** [fontvu/BTU-WebDocs-WS22#32]
Dear clients,

in your wireframe you have included breadcrumbs right under the navigation. Usually a breadcrum can help the user if the page structure is complex. You don't have many pages and each page can be found in the navigation on top which is shown the whole time. We suggest to remove the breadcrum, if you agree with this. Please let us know ASAP. 

Thanks! 

<img width="1440" alt="Screenshot 2023-01-10 at 13 10 57" src="https://user-images.githubusercontent.com/49497676/211548368-20ee9ae6-d98b-45a6-a93d-403abd6d2168.png">

**Comment by jaylin0114** [comment]
I feel that redundant as well. I can accept that. Thanks for your
suggestion.
And also the navigator now is in the top right corner, which is better as
well. Thanks for your effort.
